# Generated by Django 3.0.6 on 2020-05-05 21:30

import apps.main.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('characters_cls', models.CharField(choices=[('DRUID', 'druid'), ('WIZARD', 'wizard'), ('BARD', 'bard')], max_length=100)),
                ('characters_race', models.CharField(choices=[('HUMAN', 'human'), ('ELF', 'elf'), ('HALF_ELF', 'half_elf'), ('GNOME', 'gnome'), ('HALFLING', 'halfling')], max_length=100)),
            ],
        ),
    ]
