# Generated by Django 3.0.6 on 2020-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_href', models.CharField(choices=[('HUMAN', ''), ('ELF', 'Elf'), ('HALF_ELF', 'Half_Elf'), ('GNOME', 'Gnome'), ('HALFLING', 'Halfling')], max_length=200)),
                ('cls_href', models.CharField(choices=[('DRUID', 'Druid'), ('WIZARD', 'Wizard'), ('BARD', 'Bard'), ('RANGER', 'Ranger')], max_length=200)),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterField(
            model_name='image',
            name='characters_cls',
            field=models.CharField(choices=[('DRUID', 'Druid'), ('WIZARD', 'Wizard'), ('BARD', 'Bard'), ('RANGER', 'Ranger')], max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='characters_race',
            field=models.CharField(choices=[('HUMAN', 'Human'), ('ELF', 'Elf'), ('HALF_ELF', 'Half_Elf'), ('GNOME', 'Gnome'), ('HALFLING', 'Halfling')], max_length=100),
        ),
    ]
