# Generated by Django 3.0.6 on 2020-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200515_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrefs',
            name='cls_href',
        ),
        migrations.RemoveField(
            model_name='hrefs',
            name='race_href',
        ),
        migrations.AddField(
            model_name='hrefs',
            name='cls',
            field=models.CharField(choices=[('DRUID', 'Druid'), ('WIZARD', 'Wizard'), ('BARD', 'Bard'), ('RANGER', 'Ranger')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hrefs',
            name='race',
            field=models.CharField(choices=[('HUMAN', 'Human'), ('ELF', 'Elf'), ('HALF_ELF', 'Half_Elf'), ('GNOME', 'Gnome'), ('HALFLING', 'Halfling')], default='', max_length=200),
        ),
    ]
